
default_platform(:ios)

platform :ios do
  lane :build_p12 do
	get_push_certificate(
 		force: true,
 		app_identifier: "com.iosmandroid.loodoscase",
 		save_private_key: true,
  		team_id: "9T34C2V38R",
  		username: "apps@iosmandroid.com",
 		p12_password: "loodos",
  		pem_name: "LoodosCase_CERT",
 		output_path: "../Loodos-Case/CERT",
  		new_profile: proc do |profile_path|
 		puts profile_path
  		end
	)
  end
end
